const PERSONAL_KEY = "hand-private-account-youssef-v1";
const DEBTS_KEY = "hand-private-debts-youssef-v1";
const debtSeed = [
  { id: 101, creditor: "أحمد محمود", title: "مبلغ شخصي", amount: 5000, paid: 1500, dueDate: "2026-09-20", note: "سداد على دفعات" },
  { id: 102, creditor: "البنك", title: "قسط جهاز", amount: 8000, paid: 4000, dueDate: "2026-10-05", note: "القسط المتبقي" }
];
const seed = [
  { id: 1, type: "income", title: "الراتب الشهري", amount: 18000, account: "الحساب البنكي", category: "راتب", note: "راتب سبتمبر", date: "2026-09-01" },
  { id: 2, type: "income", title: "عمل حر", amount: 4500, account: "المحفظة الإلكترونية", category: "عمل إضافي", note: "مشروع تصميم", date: "2026-09-02" },
  { id: 3, type: "expense", title: "مشتريات شخصية", amount: 1200, account: "الحساب البنكي", category: "تسوق", note: "مستلزمات الشهر", date: "2026-09-02" },
  { id: 4, type: "expense", title: "مواصلات", amount: 750, account: "نقدي", category: "تنقل", note: "", date: "2026-09-03" }
];
let transactions = [];
let debts = [];
let activeFilter = "all";
let numbersHidden = false;
const incomeCategories = ["راتب","عمل إضافي","مكافأة","استثمار","أخرى"];
const expenseCategories = ["طعام","تنقل","تسوق","ترفيه","اشتراكات","صحة","سداد ديون","أخرى"];
const body = document.querySelector("#personalLedgerBody"), empty = document.querySelector("#personalEmpty"), dialog = document.querySelector("#personalDialog"), form = document.querySelector("#personalForm"), typeInput = document.querySelector("#personalType"), categoryInput = document.querySelector("#personalCategory"), toast = document.querySelector("#toast");
const debtList = document.querySelector("#debtList"), debtDialog = document.querySelector("#debtDialog"), debtForm = document.querySelector("#debtForm"), debtPaymentDialog = document.querySelector("#debtPaymentDialog"), debtPaymentForm = document.querySelector("#debtPaymentForm");

async function request(url,options){const response=await fetch(url,options),data=await response.json();if(!response.ok)throw new Error(data.error||"تعذر الاتصال بالخادم");return data}
async function loadData(){const data=await request("/api/bootstrap");transactions=data.personalTransactions;debts=data.debts;numbersHidden=Boolean(data.settings?.hidePersonalTotals)}
function money(value){return `${new Intl.NumberFormat("en-EG",{maximumFractionDigits:2}).format(value)} ج`}
function date(value){return new Intl.DateTimeFormat("ar-EG",{day:"numeric",month:"short",year:"numeric"}).format(new Date(value))}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char])}
function totals(){const income=transactions.filter(item=>item.type==="income").reduce((sum,item)=>sum+Number(item.amount),0);const expense=transactions.filter(item=>item.type==="expense").reduce((sum,item)=>sum+Number(item.amount),0);return{income,expense,balance:income-expense}}

function renderSummary(){const{income,expense,balance}=totals();document.querySelector("#personalBalance").textContent=money(balance);document.querySelector("#personalIncome").textContent=money(income);document.querySelector("#personalExpense").textContent=money(expense);document.querySelector("#savingRate").textContent=income?`${Math.round(balance/income*100)}%`:"0%";document.querySelector("#incomeCount").textContent=`${transactions.filter(item=>item.type==="income").length} حركات`;document.querySelector("#expenseCount").textContent=`${transactions.filter(item=>item.type==="expense").length} حركات`;document.querySelector("#balanceMessage").textContent=balance<0?`عجز شخصي بقيمة ${money(Math.abs(balance))}`:"متاح للاستخدام"}
function running(){let balance=0;return[...transactions].sort((a,b)=>a.id-b.id).map(item=>{balance+=item.type==="income"?Number(item.amount):-Number(item.amount);return{...item,runningBalance:balance}}).reverse()}
function renderLedger(){const items=running().filter(item=>activeFilter==="all"||item.type===activeFilter);empty.classList.toggle("show",items.length===0);body.innerHTML=items.map(item=>`<tr><td><div class="transaction-name"><span class="transaction-symbol ${item.type}">${item.type==="income"?"↓":"↑"}</span><div><strong>${escapeHtml(item.title)}</strong><small>${escapeHtml(item.note||"بدون ملاحظة")}</small></div></div></td><td>${escapeHtml(item.account)}</td><td>${escapeHtml(item.category)}</td><td>${date(item.date)}</td><td><span class="transaction-amount private-amount ${item.type}">${item.type==="income"?"+":"−"}${money(item.amount)}</span></td><td><span class="running-balance private-amount ${item.runningBalance<0?"negative":""}">${money(item.runningBalance)}</span></td></tr>`).join("")}
function renderDebts(){const remaining=debts.reduce((sum,item)=>sum+Math.max(0,Number(item.amount)-Number(item.paid)),0),paid=debts.reduce((sum,item)=>sum+Number(item.paid),0),active=debts.filter(item=>Number(item.paid)<Number(item.amount));document.querySelector("#totalDebtRemaining").textContent=money(remaining);document.querySelector("#totalDebtPaid").textContent=money(paid);document.querySelector("#activeDebtCount").textContent=active.length;document.querySelector("#debtEmpty").classList.toggle("show",debts.length===0);const today=new Date().toISOString().slice(0,10);debtList.innerHTML=debts.map(item=>{const left=Math.max(0,Number(item.amount)-Number(item.paid)),progress=Math.min(100,Math.round(Number(item.paid)/Number(item.amount)*100)),settled=left===0,overdue=!settled&&item.dueDate<today,status=settled?"تم السداد":overdue?"متأخر":"قائم";return`<article class="debt-card ${settled?"settled":overdue?"overdue":""}"><div class="debt-card-head"><div class="debt-person"><span class="debt-icon">${escapeHtml(item.creditor.trim()[0]||"د")}</span><div><strong>${escapeHtml(item.title)}</strong><small>الدائن: ${escapeHtml(item.creditor)}</small></div></div><span class="debt-status ${settled?"settled":overdue?"overdue":""}">${status}</span></div><div class="debt-numbers"><div><span>المتبقي</span><strong class="private-amount">${money(left)}</strong></div><small>من أصل ${money(item.amount)}<br/>تم سداد ${progress}%</small></div><div class="debt-progress"><span style="width:${progress}%"></span></div><div class="debt-card-footer"><span>موعد السداد: ${date(item.dueDate)}</span>${settled?"":`<button class="debt-pay-btn" data-pay-debt="${item.id}">تسجيل سداد</button>`}</div></article>`}).join("");document.querySelectorAll("[data-pay-debt]").forEach(button=>button.addEventListener("click",()=>openDebtPayment(Number(button.dataset.payDebt))))}
function render(){renderSummary();renderLedger();renderDebts()}
function setType(type){typeInput.value=type;document.querySelectorAll(".personal-type-switch button").forEach(button=>button.classList.toggle("active",button.dataset.type===type));const items=type==="income"?incomeCategories:expenseCategories;categoryInput.innerHTML=items.map(item=>`<option>${item}</option>`).join("")}
function showToast(message){toast.textContent=message;toast.classList.add("show");window.setTimeout(()=>toast.classList.remove("show"),2400)}

document.querySelector("#addPersonalTransaction").addEventListener("click",()=>{setType("income");dialog.showModal()});
document.querySelectorAll(".personal-type-switch button").forEach(button=>button.addEventListener("click",()=>setType(button.dataset.type)));
document.querySelector("#closePersonalDialog").addEventListener("click",()=>dialog.close());document.querySelector("#cancelPersonal").addEventListener("click",()=>dialog.close());
form.addEventListener("submit",async event=>{event.preventDefault();const payload={type:typeInput.value,title:document.querySelector("#personalTitle").value.trim(),amount:Number(document.querySelector("#personalAmount").value),account:document.querySelector("#personalAccount").value,category:categoryInput.value,note:document.querySelector("#personalNote").value.trim(),date:new Date().toISOString().slice(0,10)};try{transactions.push(await request("/api/personal-transactions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}));render();form.reset();dialog.close();showToast("تم حفظ الحركة في حسابك الخاص")}catch(error){showToast(error.message)}});
document.querySelector("#addDebt").addEventListener("click",()=>{document.querySelector("#debtDueDate").value=new Date().toISOString().slice(0,10);debtDialog.showModal()});document.querySelector("#closeDebtDialog").addEventListener("click",()=>debtDialog.close());document.querySelector("#cancelDebt").addEventListener("click",()=>debtDialog.close());
debtForm.addEventListener("submit",async event=>{event.preventDefault();const amount=Number(document.querySelector("#debtAmount").value),paid=Number(document.querySelector("#debtInitiallyPaid").value);if(paid>amount){showToast("المبلغ المدفوع لا يمكن أن يتجاوز إجمالي الدين");return}const payload={creditor:document.querySelector("#debtCreditor").value.trim(),title:document.querySelector("#debtTitle").value.trim(),amount,paid,dueDate:document.querySelector("#debtDueDate").value,note:document.querySelector("#debtNote").value.trim()};try{debts.push(await request("/api/debts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}));render();debtForm.reset();debtDialog.close();showToast("تم حفظ الدين في حسابك الشخصي")}catch(error){showToast(error.message)}});
function openDebtPayment(id){const debt=debts.find(item=>item.id===id);if(!debt)return;const remaining=Math.max(0,debt.amount-debt.paid);document.querySelector("#paymentDebtId").value=id;document.querySelector("#paymentDebtName").textContent=`${debt.title} — ${debt.creditor}`;document.querySelector("#paymentRemaining").textContent=`المتبقي حاليًا: ${money(remaining)}`;const input=document.querySelector("#debtPaymentAmount");input.value="";input.max=remaining;debtPaymentDialog.showModal()}
document.querySelector("#closeDebtPayment").addEventListener("click",()=>debtPaymentDialog.close());document.querySelector("#cancelDebtPayment").addEventListener("click",()=>debtPaymentDialog.close());
debtPaymentForm.addEventListener("submit",async event=>{event.preventDefault();const id=Number(document.querySelector("#paymentDebtId").value),debt=debts.find(item=>item.id===id),payment=Number(document.querySelector("#debtPaymentAmount").value);if(!debt||payment<=0||payment>debt.amount-debt.paid){showToast("أدخل مبلغًا صحيحًا لا يتجاوز المتبقي");return}try{const updated=await request(`/api/debts/${id}/payments`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({amount:payment,account:"نقدي"})});debts=debts.map(item=>item.id===id?updated:item);transactions=await request("/api/personal-transactions");render();debtPaymentDialog.close();showToast("تم تسجيل السداد وتحديث حسابك الشخصي")}catch(error){showToast(error.message)}});
document.querySelectorAll(".personal-filters button").forEach(button=>button.addEventListener("click",()=>{activeFilter=button.dataset.filter;document.querySelectorAll(".personal-filters button").forEach(item=>item.classList.toggle("active",item===button));renderLedger()}));
document.querySelector("#hideBalances").addEventListener("click",()=>{numbersHidden=!numbersHidden;document.querySelector(".personal-content").classList.toggle("hide-private",numbersHidden);document.querySelector("#hideBalances span").textContent=numbersHidden?"إظهار الأرقام":"إخفاء الأرقام"});

const sidebar=document.querySelector("#sidebar"),menuBtn=document.querySelector("#menuBtn");menuBtn.addEventListener("click",()=>{const open=sidebar.classList.toggle("open");menuBtn.setAttribute("aria-expanded",String(open))});
const profileMenu=document.querySelector("#profileMenu"),profileBtn=document.querySelector("#profileBtn"),profileDropdown=document.querySelector("#profileDropdown");profileBtn.addEventListener("click",()=>{const open=!profileDropdown.classList.contains("open");profileDropdown.classList.toggle("open",open);profileBtn.setAttribute("aria-expanded",String(open));profileDropdown.setAttribute("aria-hidden",String(!open))});document.addEventListener("click",event=>{if(!profileMenu.contains(event.target)){profileDropdown.classList.remove("open");profileBtn.setAttribute("aria-expanded","false")}});document.querySelectorAll(".dropdown-item").forEach(item=>{if(item.textContent.includes("الدعم")){item.addEventListener("click",()=>{window.location.href="support.html"})}});document.querySelector("#logoutBtn").addEventListener("click",()=>{window.location.href="index.html"});
setType("income");loadData().then(()=>{render();if(numbersHidden){document.querySelector(".personal-content").classList.add("hide-private");document.querySelector("#hideBalances span").textContent="إظهار الأرقام"}}).catch(error=>showToast(error.message));
