const toast=document.querySelector("#toast");let user=null;
function showToast(message){toast.textContent=message;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2400)}
async function request(url,options){const response=await fetch(url,options),data=await response.json();if(!response.ok)throw new Error(data.error||"حدث خطأ");return data}
function paint(){const role=user.role==="manager"?"مدير السكن":"مشترك";document.querySelector("#profileName").textContent=user.name;document.querySelector("#profileRole").textContent=role;document.querySelector("#profileEmail").textContent=user.email;document.querySelector("#profileNameInput").value=user.name;document.querySelector("#profileEmailInput").value=user.email;document.querySelector("#profilePhoneInput").value=user.phone||"";document.querySelector("#profileAvatarLarge").src=user.avatarUrl||"assets/profile-youssef.png"}
request("/api/me").then(data=>{user=data.user;paint()}).catch(()=>location.replace("index.html"));
const form=document.querySelector("#profileForm"),inputs=form.querySelectorAll("input"),actions=document.querySelector("#profileFormActions"),edit=document.querySelector("#editProfileBtn");
edit.addEventListener("click",()=>{inputs.forEach(input=>input.readOnly=false);actions.style.display="grid";edit.style.display="none"});
document.querySelector("#cancelProfile").addEventListener("click",()=>{paint();inputs.forEach(input=>input.readOnly=true);actions.style.display="none";edit.style.display="block"});
form.addEventListener("submit",async event=>{event.preventDefault();try{const data=await request("/api/me",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:document.querySelector("#profileNameInput").value,email:document.querySelector("#profileEmailInput").value,phone:document.querySelector("#profilePhoneInput").value})});user=data.user;paint();inputs.forEach(input=>input.readOnly=true);actions.style.display="none";edit.style.display="block";showToast("تم تحديث بياناتك")}catch(error){showToast(error.message)}});
document.querySelector("#passwordForm").addEventListener("submit",async event=>{event.preventDefault();const currentPassword=document.querySelector("#currentPassword").value,newPassword=document.querySelector("#newPassword").value,confirm=document.querySelector("#confirmPassword").value;if(newPassword!==confirm){showToast("كلمة المرور الجديدة غير متطابقة");return}try{await request("/api/me/password",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword,newPassword})});event.target.reset();showToast("تم تغيير كلمة المرور")}catch(error){showToast(error.message)}});
const sidebar=document.querySelector("#sidebar"),menuBtn=document.querySelector("#menuBtn"),profileMenu=document.querySelector("#profileMenu"),profileBtn=document.querySelector("#profileBtn"),profileDropdown=document.querySelector("#profileDropdown");menuBtn.addEventListener("click",()=>sidebar.classList.toggle("open"));profileBtn.addEventListener("click",()=>profileDropdown.classList.toggle("open"));document.addEventListener("click",event=>{if(!profileMenu.contains(event.target))profileDropdown.classList.remove("open")});document.querySelectorAll(".dropdown-item").forEach(item=>{if(item.textContent.includes("الدعم"))item.addEventListener("click",()=>location.href="support.html")});
