const housingSeed = [
  { id:1,type:"income",party:"محمد علي",amount:1580,category:"اشتراك السكن",date:"2026-09-01" },
  { id:2,type:"income",party:"عمر خالد",amount:1580,category:"اشتراك السكن",date:"2026-09-01" },
  { id:3,type:"income",party:"يوسف أحمد",amount:1580,category:"اشتراك السكن",date:"2026-09-02" },
  { id:4,type:"expense",party:"فاتورة الغاز",amount:120,category:"غاز",date:"2026-09-02" },
  { id:5,type:"expense",party:"مستلزمات المنزل",amount:740,category:"مستلزمات",date:"2026-09-03" }
];
const personalSeed = [
  {id:1,type:"income",title:"الراتب الشهري",amount:18000,category:"راتب",date:"2026-09-01"},
  {id:2,type:"income",title:"عمل حر",amount:4500,category:"عمل إضافي",date:"2026-09-02"},
  {id:3,type:"expense",title:"مشتريات شخصية",amount:1200,category:"تسوق",date:"2026-09-02"},
  {id:4,type:"expense",title:"مواصلات",amount:750,category:"تنقل",date:"2026-09-03"}
];
const scopeInput=document.querySelector("#reportScope"),monthInput=document.querySelector("#reportMonth"),tableBody=document.querySelector("#reportTableBody"),chart=document.querySelector("#movementChart"),breakdown=document.querySelector("#breakdownList");

let reportData={housing:[],personal:[]};
async function loadData(){const response=await apiFetch("/api/bootstrap"),data=await response.json();if(!response.ok)throw new Error(data.error||"تعذر تحميل التقارير");reportData.housing=data.housingTransactions.map(item=>({...item,category:item.category?.name||"أخرى",date:String(item.date).slice(0,10)}));reportData.personal=data.personalTransactions.map(item=>({...item,date:String(item.date).slice(0,10)}))}
function readData(scope){return reportData[scope]||[]}
function money(value){return `${new Intl.NumberFormat("en-EG",{maximumFractionDigits:2}).format(value)} ج`}
function date(value){return new Intl.DateTimeFormat("ar-EG",{day:"numeric",month:"short",year:"numeric"}).format(new Date(value))}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char])}
function selectedData(){return readData(scopeInput.value).filter(item=>String(item.date||"").startsWith(monthInput.value))}

function renderSummary(items){const incomes=items.filter(item=>item.type==="income"),expenses=items.filter(item=>item.type==="expense");const income=incomes.reduce((sum,item)=>sum+Number(item.amount),0),expense=expenses.reduce((sum,item)=>sum+Number(item.amount),0),net=income-expense,average=expenses.length?expense/expenses.length:0;document.querySelector("#reportIncome").textContent=money(income);document.querySelector("#reportExpense").textContent=money(expense);document.querySelector("#reportNet").textContent=money(net);document.querySelector("#reportAverage").textContent=money(average);document.querySelector("#reportIncomeCount").textContent=`${incomes.length} حركات`;document.querySelector("#reportExpenseCount").textContent=`${expenses.length} حركات`;document.querySelector("#reportNetState").textContent=net<0?"عجز خلال الشهر":"رصيد موجب";document.querySelector(".report-stat.net").classList.toggle("negative",net<0)}
function renderChart(items){const grouped={};items.forEach(item=>{const day=Number(item.date.slice(-2));grouped[day]??={income:0,expense:0};grouped[day][item.type]+=Number(item.amount)});const days=Object.keys(grouped).map(Number).sort((a,b)=>a-b),max=Math.max(1,...days.flatMap(day=>[grouped[day].income,grouped[day].expense]));chart.classList.toggle("hidden",days.length===0);document.querySelector("#chartEmpty").classList.toggle("show",days.length===0);chart.innerHTML=days.map(day=>`<div class="chart-day"><div class="chart-bars"><span class="chart-bar income" style="height:${Math.max(2,grouped[day].income/max*205)}px" title="داخل ${money(grouped[day].income)}"></span><span class="chart-bar expense" style="height:${Math.max(2,grouped[day].expense/max*205)}px" title="خارج ${money(grouped[day].expense)}"></span></div><small>${day}</small></div>`).join("")}
function renderBreakdown(items){const expenses=items.filter(item=>item.type==="expense"),groups={};expenses.forEach(item=>groups[item.category]=(groups[item.category]||0)+Number(item.amount));const entries=Object.entries(groups).sort((a,b)=>b[1]-a[1]),total=expenses.reduce((sum,item)=>sum+Number(item.amount),0);document.querySelector("#breakdownEmpty").classList.toggle("show",entries.length===0);breakdown.innerHTML=entries.map(([name,value])=>{const percent=total?Math.round(value/total*100):0;return`<div class="breakdown-item"><div class="breakdown-item-head"><span>${escapeHtml(name)}</span><strong>${money(value)}</strong></div><div class="breakdown-track"><span style="width:${percent}%"></span></div><small class="breakdown-meta">${percent}% من إجمالي المصروفات</small></div>`}).join("")}
function renderTable(items){document.querySelector("#reportCount").textContent=`${items.length} حركة`;document.querySelector("#reportEmpty").classList.toggle("show",items.length===0);tableBody.innerHTML=[...items].sort((a,b)=>String(b.date).localeCompare(String(a.date))||b.id-a.id).map(item=>`<tr><td><div class="transaction-name"><span class="transaction-symbol ${item.type}">${item.type==="income"?"↓":"↑"}</span><strong>${escapeHtml(item.party||item.title||"حركة مالية")}</strong></div></td><td>${escapeHtml(item.category||"أخرى")}</td><td>${date(item.date)}</td><td><span class="report-kind ${item.type}">${item.type==="income"?"داخل":"خارج"}</span></td><td><span class="transaction-amount ${item.type}">${item.type==="income"?"+":"−"}${money(item.amount)}</span></td></tr>`).join("")}
function render(){const personal=scopeInput.value==="personal",items=selectedData();document.querySelector("#reportTitle").textContent=personal?"تقرير حساباتي الشخصية":"تقرير حسابات السكن";document.querySelector("#reportDescription").textContent=personal?"تقرير خاص بك فقط يعرض دخلك ومصروفاتك الشخصية.":"يعرض الحركات المشتركة التي دخلت وخرجت من محفظة السكن.";document.querySelector("#sidebarReportName").textContent=personal?"حساباتي الشخصية":"حسابات السكن";renderSummary(items);renderChart(items);renderBreakdown(items);renderTable(items)}
scopeInput.addEventListener("change",render);monthInput.addEventListener("change",render);document.querySelector("#printReport").addEventListener("click",()=>window.print());window.addEventListener("pageshow",()=>loadData().then(render));
const sidebar=document.querySelector("#sidebar"),menuBtn=document.querySelector("#menuBtn");menuBtn.addEventListener("click",()=>{const open=sidebar.classList.toggle("open");menuBtn.setAttribute("aria-expanded",String(open))});const profileMenu=document.querySelector("#profileMenu"),profileBtn=document.querySelector("#profileBtn"),profileDropdown=document.querySelector("#profileDropdown");profileBtn.addEventListener("click",()=>{const open=!profileDropdown.classList.contains("open");profileDropdown.classList.toggle("open",open);profileBtn.setAttribute("aria-expanded",String(open));profileDropdown.setAttribute("aria-hidden",String(!open))});document.addEventListener("click",event=>{if(!profileMenu.contains(event.target)){profileDropdown.classList.remove("open");profileBtn.setAttribute("aria-expanded","false")}});document.querySelectorAll(".dropdown-item").forEach(item=>{if(item.textContent.includes("الدعم")){item.addEventListener("click",()=>{window.location.href="support.html"})}});document.querySelector("#logoutBtn").addEventListener("click",()=>{window.location.href="index.html"});
loadData().then(render).catch(()=>render());
