const SETTINGS_KEY="hand-settings-v1";
const defaults={residenceName:"سكن النخيل",residentCount:6,currency:"EGP",monthStart:1,splitMethod:"equal",includeManager:true,dueReminder:true,lowBalanceAlert:true,transactionAlert:false,reminderDays:3,theme:"dark",hidePersonalTotals:false,requireLogin:true};
let settings={...defaults};
const form=document.querySelector("#settingsForm"),toast=document.querySelector("#toast");
async function request(url,options){const response=await fetch(url,options),data=await response.json();if(!response.ok)throw new Error(data.error||"تعذر الاتصال بالخادم");return data}
function money(value){return `${new Intl.NumberFormat("en-EG",{maximumFractionDigits:2}).format(value)} ج`}
let monthlyTotal=8400;function monthlyExpenseTotal(){return monthlyTotal}
function fillForm(){document.querySelector("#residenceName").value=settings.residenceName;document.querySelector("#residentCount").value=settings.residentCount;document.querySelector("#currency").value=settings.currency;document.querySelector("#monthStart").value=settings.monthStart;document.querySelector(`[name="splitMethod"][value="${settings.splitMethod}"]`).checked=true;document.querySelector("#includeManager").checked=settings.includeManager;document.querySelector("#dueReminder").checked=settings.dueReminder;document.querySelector("#lowBalanceAlert").checked=settings.lowBalanceAlert;document.querySelector("#transactionAlert").checked=settings.transactionAlert;document.querySelector("#reminderDays").value=settings.reminderDays;document.querySelector("#hidePersonalTotals").checked=settings.hidePersonalTotals;document.querySelector("#requireLogin").checked=settings.requireLogin;const theme=document.documentElement.dataset.theme;document.querySelector(`[name="themeSetting"][value="${theme}"]`).checked=true;updatePreview()}
function updatePreview(){const total=monthlyExpenseTotal(),count=Math.max(1,Number(document.querySelector("#residentCount").value)||1),includeManager=document.querySelector("#includeManager").checked,people=Math.max(1,includeManager?count:count-1);document.querySelector("#settingsMonthlyTotal").textContent=money(total);document.querySelector("#settingsPeopleCount").textContent=people;document.querySelector("#estimatedShare").textContent=money(total/people);document.querySelector("#settingsSideHome").textContent=document.querySelector("#residenceName").value||"السكن";document.querySelector("#settingsSideCount").textContent=`${count} أفراد`}
document.querySelector("#residentCount").addEventListener("input",updatePreview);document.querySelector("#residenceName").addEventListener("input",updatePreview);document.querySelector("#includeManager").addEventListener("change",updatePreview);
document.querySelectorAll('[name="themeSetting"]').forEach(input=>input.addEventListener("change",()=>{document.documentElement.dataset.theme=input.value;localStorage.setItem("hand-color-theme",input.value)}));
form.addEventListener("submit",async event=>{event.preventDefault();settings={residenceName:document.querySelector("#residenceName").value.trim(),residentCount:Number(document.querySelector("#residentCount").value),currency:document.querySelector("#currency").value,monthStart:Number(document.querySelector("#monthStart").value),splitMethod:document.querySelector('[name="splitMethod"]:checked').value,includeManager:document.querySelector("#includeManager").checked,dueReminder:document.querySelector("#dueReminder").checked,lowBalanceAlert:document.querySelector("#lowBalanceAlert").checked,transactionAlert:document.querySelector("#transactionAlert").checked,reminderDays:Number(document.querySelector("#reminderDays").value),theme:document.documentElement.dataset.theme,hidePersonalTotals:document.querySelector("#hidePersonalTotals").checked,requireLogin:document.querySelector("#requireLogin").checked};try{settings=await request("/api/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(settings)});toast.textContent="تم حفظ الإعدادات بنجاح"}catch(error){toast.textContent=error.message}toast.classList.add("show");window.setTimeout(()=>toast.classList.remove("show"),2400)});
const sidebar=document.querySelector("#sidebar"),menuBtn=document.querySelector("#menuBtn");menuBtn.addEventListener("click",()=>{const open=sidebar.classList.toggle("open");menuBtn.setAttribute("aria-expanded",String(open))});const profileMenu=document.querySelector("#profileMenu"),profileBtn=document.querySelector("#profileBtn"),profileDropdown=document.querySelector("#profileDropdown");profileBtn.addEventListener("click",()=>{const open=!profileDropdown.classList.contains("open");profileDropdown.classList.toggle("open",open);profileBtn.setAttribute("aria-expanded",String(open));profileDropdown.setAttribute("aria-hidden",String(!open))});document.addEventListener("click",event=>{if(!profileMenu.contains(event.target)){profileDropdown.classList.remove("open");profileBtn.setAttribute("aria-expanded","false")}});document.querySelectorAll(".dropdown-item").forEach(item=>{if(item.textContent.includes("الدعم")){item.addEventListener("click",()=>{window.location.href="support.html"})}});document.querySelector("#logoutBtn").addEventListener("click",()=>{window.location.href="index.html"});
request("/api/bootstrap").then(data=>{settings={...defaults,...data.settings};monthlyTotal=data.categories.filter(item=>item.type==="expense"&&item.frequency==="monthly").reduce((sum,item)=>sum+Number(item.amount),0);fillForm()}).catch(error=>{toast.textContent=error.message;toast.classList.add("show")});
