const SUBSCRIBERS_KEY="hand-subscribers-v1";
const seed=[
  {id:1,name:"يوسف أحمد",email:"youssef@hand.app",phone:"01012345678",role:"manager",share:1580,joinDate:"2026-01-10",status:"active"},
  {id:2,name:"محمد علي",email:"mohamed@hand.app",phone:"01123456789",role:"resident",share:1580,joinDate:"2026-02-01",status:"active"},
  {id:3,name:"عمر خالد",email:"omar@hand.app",phone:"01234567890",role:"resident",share:1580,joinDate:"2026-02-15",status:"active"},
  {id:4,name:"أحمد سامي",email:"ahmed@hand.app",phone:"01098765432",role:"resident",share:1580,joinDate:"2026-03-01",status:"active"},
  {id:5,name:"كريم حسن",email:"karim@hand.app",phone:"01187654321",role:"resident",share:1580,joinDate:"2026-04-12",status:"pending"},
  {id:6,name:"محمود طارق",email:"mahmoud@hand.app",phone:"01276543210",role:"resident",share:1580,joinDate:"2026-05-20",status:"disabled"}
];
let subscribers=[];
const body=document.querySelector("#subscribersBody"),empty=document.querySelector("#subscribersEmpty"),search=document.querySelector("#subscriberSearch"),statusFilter=document.querySelector("#subscriberStatus"),dialog=document.querySelector("#subscriberDialog"),form=document.querySelector("#subscriberForm"),toast=document.querySelector("#toast");

async function request(url,options){const response=await apiFetch(url,options),data=await response.json();if(!response.ok)throw new Error(data.error||"تعذر الاتصال بالخادم");return data}
function money(value){return `${new Intl.NumberFormat("en-EG",{maximumFractionDigits:2}).format(value)} ج`}
function date(value){return new Intl.DateTimeFormat("ar-EG",{day:"numeric",month:"short",year:"numeric"}).format(new Date(value))}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char])}
function initials(name){return name.trim().split(/\s+/).slice(0,2).map(part=>part[0]).join("")}
function statusText(status){return{active:"نشط",pending:"دعوة معلقة",disabled:"موقوف"}[status]}

function renderSummary(){const active=subscribers.filter(item=>item.status==="active"),pending=subscribers.filter(item=>item.status==="pending");document.querySelector("#allSubscribers").textContent=subscribers.length;document.querySelector("#activeSubscribers").textContent=active.length;document.querySelector("#pendingSubscribers").textContent=pending.length;document.querySelector("#expectedSubscriptions").textContent=money(active.reduce((sum,item)=>sum+Number(item.monthlyShare),0));document.querySelector("#sideSubscribersCount").textContent=`${subscribers.length} مشتركين`}
function renderTable(){const query=search.value.trim().toLowerCase(),status=statusFilter.value;const visible=subscribers.filter(item=>(status==="all"||item.status===status)&&(!query||item.name.toLowerCase().includes(query)||item.email.toLowerCase().includes(query)||String(item.phone||"").includes(query)));empty.classList.toggle("show",visible.length===0);body.innerHTML=visible.map(item=>`<tr><td><div class="subscriber-user"><span class="subscriber-avatar">${escapeHtml(initials(item.name))}</span><div><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.email)}</small></div></div></td><td dir="ltr">${escapeHtml(item.phone||"—")}</td><td><span class="subscriber-role">${item.role==="manager"?"مدير السكن":"مشترك"}</span></td><td>${money(item.monthlyShare)}</td><td>${date(item.joinDate)}</td><td><span class="account-status ${item.status}">${statusText(item.status)}</span></td><td><button class="account-action" data-toggle="${item.id}">${item.status==="active"?"إيقاف":"تفعيل"}</button></td></tr>`).join("");document.querySelectorAll("[data-toggle]").forEach(button=>button.addEventListener("click",async()=>{const user=subscribers.find(item=>item.id===Number(button.dataset.toggle));if(!user)return;const status=user.status==="active"?"disabled":"active";try{const updated=await request(`/api/users/${user.id}/status`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});Object.assign(user,updated);render();showToast(status==="active"?"تم تفعيل الحساب":"تم إيقاف الحساب")}catch(error){showToast(error.message)}}))}
function render(){renderSummary();renderTable()}
function showToast(message){toast.textContent=message;toast.classList.add("show");window.setTimeout(()=>toast.classList.remove("show"),2400)}
search.addEventListener("input",renderTable);statusFilter.addEventListener("change",renderTable);
document.querySelector("#addSubscriber").addEventListener("click",()=>{document.querySelector("#subscriberJoinDate").value=new Date().toISOString().slice(0,10);dialog.showModal()});document.querySelector("#closeSubscriberDialog").addEventListener("click",()=>dialog.close());document.querySelector("#cancelSubscriber").addEventListener("click",()=>dialog.close());
form.addEventListener("submit",async event=>{event.preventDefault();const email=document.querySelector("#subscriberEmail").value.trim().toLowerCase();if(subscribers.some(item=>item.email.toLowerCase()===email)){showToast("البريد الإلكتروني مسجل بالفعل");return}const payload={name:document.querySelector("#subscriberName").value.trim(),email,phone:document.querySelector("#subscriberPhone").value.trim(),role:document.querySelector("#subscriberRole").value,share:Number(document.querySelector("#subscriberShare").value),joinDate:document.querySelector("#subscriberJoinDate").value,status:document.querySelector("#subscriberAccountStatus").value};try{subscribers.push(await request("/api/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}));render();form.reset();dialog.close();showToast("تم إنشاء حساب المشترك")}catch(error){showToast(error.message)}});

const sidebar=document.querySelector("#sidebar"),menuBtn=document.querySelector("#menuBtn");menuBtn.addEventListener("click",()=>{const open=sidebar.classList.toggle("open");menuBtn.setAttribute("aria-expanded",String(open))});const profileMenu=document.querySelector("#profileMenu"),profileBtn=document.querySelector("#profileBtn"),profileDropdown=document.querySelector("#profileDropdown");profileBtn.addEventListener("click",()=>{const open=!profileDropdown.classList.contains("open");profileDropdown.classList.toggle("open",open);profileBtn.setAttribute("aria-expanded",String(open));profileDropdown.setAttribute("aria-hidden",String(!open))});document.addEventListener("click",event=>{if(!profileMenu.contains(event.target)){profileDropdown.classList.remove("open");profileBtn.setAttribute("aria-expanded","false")}});document.querySelectorAll(".dropdown-item").forEach(item=>{if(item.textContent.includes("الدعم")){item.addEventListener("click",()=>{window.location.href="support.html"})}});document.querySelector("#logoutBtn").addEventListener("click",()=>{window.location.href="index.html"});
request("/api/users").then(data=>{subscribers=data;render()}).catch(error=>showToast(error.message));
